# Generated by Django 4.2.20 on 2025-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_discount_price_product_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cтоимость c учетом скидки'),
        ),
    ]
