# Generated by Django 4.2.20 on 2025-04-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_rate',
        ),
    ]
