# Generated by Django 4.2.20 on 2025-04-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_favorite'),
        ('product', '0006_basket'),
    ]

    operations = [
    ]
