# Generated by Django 4.2.20 on 2025-04-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_favorite_product'),
        ('product', '0009_qr_orderrequest'),
    ]

    operations = [
    ]
